### ISSUE TITLE
Error When Running Database Backup

### ISSUE THREAD

**Issue by baberuth22** [webula-cz/smallbackup#1]
When I click backup now on the database tab I see the following error:

"Undefined constant Doctrine\DBAL\Types\Type::STRING" on line 305 of /Users/bryansaltzman/www/valetsites/neatquiz/plugins/webula/smallbackup/classes/drivers/Mysql.php

Any ideas? Thanks :)

**Comment by jan-vince** [comment]
What is your DB type and October version?

You can remap database types in plugin's settings (tab Settings):

Database type: STRING
Doctrine type: TEXT

**Comment by Rike-cz** [comment]
Since Doctrine 3 there is some class refactoring. To stay supporting old October CMS v1 I did little fix. Please try this commit: https://github.com/webula-cz/smallbackup/commit/30239509fbf21885a888b5034996a855e0dbd2fa and tell us.
